# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.1
  - 1.2
  - 1.3
  - nightly
notifications:
  email: false

codecov: true
coveralls: true

jobs:
  allow_failures:
   - julia: nightly
   - os: windows
#  include:
#    - stage: "Documentation"
#      julia: 1.1
#      os: linux
#      script:
#        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
#                                               Pkg.instantiate()'
#        - julia --project=docs/ docs/make.jl
#      after_success: skip

after_success:
 - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'
